### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dhruvkanth** [SE310-1/W.A.K#35]
**What Is your feature request? Please describe.**
Finishing the documentationn, that informs others on how to get started with the application. and to add comments

**What is the need of this feature?**
For users or other developers to run this app locally.

**Who is this feature for?**
All users/developers who want to learn more or contribute.

**Additional context**
N/A

**Comment by klam656** [comment]
We found that previous group does not comment it well, so we decide to reopen the issue.

**Comment by samcordner** [comment]
Comments are now up-to-date, as of release 2.0.0
