### ISSUE TITLE
Add Other User as a Friend

### ISSUE THREAD

**Issue by MRlolface249** [SE310-1/W.A.K#55]
## User Story

As a User,
I want to be able to add other users as friends
So that I can check on and compare profiles with them.

## Additional Context

Create functionality which allows the user to add another user as a friend and then allows them to view their friends details in some way.

## Acceptance Criteria

- [x] user can search for another user
- [x] once user is found they can then be added as a friend
- [x] user cannot 'friend' themself
- [x] friends cannot be 're-added'
- [x] friend requests persist so user does not request the same user twice
- [x] user can view details about their friends profile #80

**Comment by samcordner** [comment]
Closed by #90
