### ISSUE TITLE
Google/Facebook Authentication

### ISSUE THREAD

**Issue by MRlolface249** [SE310-1/W.A.K#79]
## User Story

As a user,
I want to be able to sign in using my Google or Facebook account,
So that I don't need to create an account for the website, and the authentication is more secure.

## Additional Context

When the user goes to sign in we would like to give them the option of signing in using their Google or Facebook account, as well as being able to create an account, this will allow users who have a Google or Facebook account a way to more easily and securely sign in to the site, but still allows users who do not have either account to still be able to sign in and use the site

## Acceptance Criteria

- [x] When user goes to sign in they are presented with the ability to sign in with a W.A.K account.
- [x] When user goes to sign in they are presented with the ability to sign in with a Google account.
- [x] When user goes to sign in they are presented with the ability to sign in with a Facebook account.
- [x] Sign in page UI should reflect these changes with styling consistent with the rest of the website.
- [x] When a Google or Facebook account is first used to sign in, site will create a user profile attached to the account.

**Comment by leas022** [comment]
Completed with PR #98
